# Generated by Django 2.2.2 on 2019-06-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_habilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo1', models.CharField(max_length=50)),
                ('TempoCargoEmAnosCargo1', models.IntegerField()),
                ('Cargo2', models.CharField(blank=True, max_length=50, null=True)),
                ('TempoCargoEmAnosCargo2', models.IntegerField(blank=True, null=True)),
                ('id_experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.dadoPessoal')),
            ],
        ),
    ]
