# Generated by Django 2.2.2 on 2019-06-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadopessoal',
            old_name='CPF',
            new_name='meu_cpf',
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
